import uuid
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class HybridSearchInput(BaseModel):
    """Input parameters for retrieving recipes using hybrid search."""

    intent_query: str = Field(
        description="The detailed natural language query describing the desired recipe type, cuisine, or flavor profile."
    )
    user_id: uuid.UUID = Field(
        description="The UUID of the authenticated user requesting the recipe candidates."
    )
    exclude_ids: Optional[List[uuid.UUID]] = Field(
        default_factory=list,
        description="A list of Recipe UUIDs that the system should exclude (e.g., recipes rated 'too hard').",
    )
    similarity_threshold: Optional[float] = Field(
        default=0.7,
        description="The minimum semantic similarity score (0.0 to 1.0) required to consider a recipe relevant. Default is 0.7.",
    )
    limit: Optional[int] = Field(
        default=10, description="The maximum number of recipe candidates to return."
    )


class FinalPlanOutput(BaseModel):
    """The final list of Recipe IDs selected for the weekly plan."""

    # We want a clean list of 7 UUIDs
    final_recipe_ids: List[uuid.UUID] = Field(
        description="The definitive list of 7 (or user.frequency) Recipe UUIDs selected for the user's weekly plan."
    )


class NewRecipeSchema(BaseModel):
    """The structured format for a new recipe generated by the LLM."""

    name: str = Field(description="The short, descriptive name of the new recipe.")
    cuisine: str = Field(
        description="The primary cuisine category (e.g., Italian, Chinese)."
    )
    ingredients: str = Field(
        description="The list of ingredients in JSON string format."
    )
    instructions: str = Field(
        description="Step-by-step cooking instructions, in clean text format."
    )
    difficulty: Literal["easy", "medium", "hard"] = Field(
        description="The estimated difficulty level."
    )
