import uuid
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class HybridSearchInput(BaseModel):
    """Input parameters for retrieving recipes using hybrid search."""

    intent_query: str = Field(
        description="The detailed natural language query describing the desired recipe type, cuisine, or flavor profile."
    )
    user_id: str = Field(
        description="The UUID string of the authenticated user requesting the recipe candidates."
    )
    exclude_ids: Optional[List[str]] = Field(
        default_factory=list,
        description="A list of Recipe UUID strings that the system should exclude (e.g., recipes rated 'too hard').",
    )
    similarity_threshold: Optional[float] = Field(
        default=0.3,
        description="The minimum semantic similarity score (0.0 to 1.0) required to consider a recipe relevant. Default is 0.3.",
    )
    limit: Optional[int] = Field(
        default=10, description="The maximum number of recipe candidates to return."
    )


class FinalPlanOutput(BaseModel):
    """The final list of Recipe IDs selected for the weekly plan."""

    final_recipe_ids: List[str] = Field(
        description="The definitive list of 7 (or user.frequency) Recipe UUID strings selected for the user's weekly plan."
    )


class RecipeSelectionInput(BaseModel):
    """Input for finalizing recipe selection."""

    recipe_ids: List[str] = Field(
        description="List of recipe IDs (as strings) to include in the weekly meal plan."
    )


class IngredientItem(BaseModel):
    """A single ingredient with its name and measurement."""

    name: str = Field(
        description="The name of the ingredient (e.g., 'Cashew nuts', 'Onions')"
    )
    measure: str = Field(
        description="The measurement or quantity (e.g., '12', '½ tbsp', '3 sliced thinly')"
    )


class NewRecipeSchema(BaseModel):
    """The structured format for a new recipe generated by the LLM."""

    name: str = Field(description="The short, descriptive name of the new recipe.")
    cuisine: str = Field(
        description="The primary cuisine category (e.g., Italian, Chinese)."
    )
    ingredients: List[IngredientItem] = Field(
        description="List of ingredients, each with 'name' and 'measure' fields."
    )
    instructions: str = Field(
        description="Step-by-step cooking instructions, in clean text format."
    )
    difficulty: Literal["easy", "medium", "hard"] = Field(
        description="The estimated difficulty level."
    )
