"""add_ai_vector_and_enhanced_feedback_columns

Revision ID: 13077c338e14
Revises: 7d9d10e55d50
Create Date: 2025-11-03 16:28:19.822435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = "13077c338e14"
down_revision: Union[str, Sequence[str], None] = "7d9d10e55d50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("content_text", sa.TEXT(), nullable=True))
    op.add_column(
        "recipes",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
    )
    op.add_column("recipes", sa.Column("is_ai_generated", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.add_column(
        "user_recipe_progress",
        sa.Column("satisfaction_rating", sa.Integer(), nullable=True),
    )
    op.add_column(
        "user_recipe_progress",
        sa.Column("difficulty_rating", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_user_recipe_progress_id"), "user_recipe_progress", ["id"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_weekly_plans_id"), "weekly_plans", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_plans_id"), table_name="weekly_plans")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_user_recipe_progress_id"), table_name="user_recipe_progress")
    op.drop_column("user_recipe_progress", "difficulty_rating")
    op.drop_column("user_recipe_progress", "satisfaction_rating")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_column("recipes", "is_ai_generated")
    op.drop_column("recipes", "embedding")
    op.drop_column("recipes", "content_text")
    # ### end Alembic commands ###
