"""create_langgraph_checkpoint_table

Revision ID: a72c1542e137
Revises: efe432010c06
Create Date: 2025-11-16 19:58:45.208271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a72c1542e137"
down_revision: Union[str, Sequence[str], None] = "efe432010c06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "langgraph_checkpoints",
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_id"),
    )
    op.create_index(
        "idx_langgraph_thread_ts",
        "langgraph_checkpoints",
        ["thread_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_langgraph_checkpoints_thread_id"),
        "langgraph_checkpoints",
        ["thread_id"],
        unique=False,
    )
    op.drop_index(
        op.f("idx_recipes_embedding"), table_name="recipes", postgresql_using="hnsw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_recipes_embedding"),
        "recipes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.drop_index(
        op.f("ix_langgraph_checkpoints_thread_id"), table_name="langgraph_checkpoints"
    )
    op.drop_index("idx_langgraph_thread_ts", table_name="langgraph_checkpoints")
    op.drop_table("langgraph_checkpoints")
    # ### end Alembic commands ###
